version: '3.8'

volumes:
  assets:
  cache:
  db:
  fcrepo:
  node_modules:
  redis:
  solr:
  uploads:
  zk:
  zoo:

networks:
  internal:

services:
  zoo:
    extends:
      file: hyrax-webapp/docker-compose.yml
      service: zoo

  solr:
    extends:
      file: hyrax-webapp/docker-compose.yml
      service: solr

  fcrepo:
    extends:
      file: hyrax-webapp/docker-compose.yml
      service: fcrepo

  db:
    extends:
      file: hyrax-webapp/docker-compose.yml
      service: db

  base:
    extends:
      file: hyrax-webapp/docker-compose.yml
      service: base
    image: ghcr.io/scientist-softserv/hykuup_knapsack/base:${TAG:-latest}
    build:
      context: .
      target: hyku-base
      cache_from:
        - ghcr.io/scientist-softserv/hykuup_knapsack/base:latest

  web:
    extends:
      file: hyrax-webapp/docker-compose.yml
      service: web
    build:
      context: .
      target: hyku-web
      cache_from:
        - ghcr.io/scientist-softserv/hykuup_knapsack/base:latest
        - ghcr.io/scientist-softserv/hykuup_knapsack:latest
    image: ghcr.io/scientist-softserv/hykuup_knapsack:${TAG:-latest}
    # command left commented for situations where the Gemfile.lock needs to be updated before the app starts
    # command: bash -l -c "bundle && ./bin/web"
    environment:
      # This line is what makes the knapsack include use the local code instead of the remote gem
      - BUNDLE_LOCAL__HYKU_KNAPSACK=/app/samvera
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=.hyku.test
    volumes:
      - node_modules:/app/samvera/hyrax-webapp/node_modules:cached
      - uploads:/app/samvera/hyrax-webapp/public/uploads:cached
      - assets:/app/samvera/hyrax-webapp/public/assets:cached
      - cache:/app/samvera/hyrax-webapp/tmp/cache:cached
      - .:/app/samvera

  worker:
    extends:
      file: hyrax-webapp/docker-compose.yml
      service: worker
    build:
      context: .
      target: hyku-worker
      cache_from:
        - ghcr.io/scientist-softserv/hykuup_knapsack/base:latest
        - ghcr.io/scientist-softserv/hykuup_knapsack:latest
        - ghcr.io/scientist-softserv/hykuup_knapsack/worker:latest
    image: ghcr.io/scientist-softserv/hykuup_knapsack/worker:${TAG:-latest}
    volumes:
      - node_modules:/app/samvera/hyrax-webapp/node_modules:cached
      - uploads:/app/samvera/hyrax-webapp/public/uploads:cached
      - assets:/app/samvera/hyrax-webapp/public/assets:cached
      - cache:/app/samvera/hyrax-webapp/tmp/cache:cached
      - .:/app/samvera

  check_volumes:
    extends:
      file: hyrax-webapp/docker-compose.yml
      service: check_volumes

  initialize_app:
    extends:
      file: hyrax-webapp/docker-compose.yml
      service: initialize_app
    # command left commented for situations where the Gemfile.lock needs to be updated before the app starts
    command:
      - >
        bundle &&
        solrcloud-upload-configset.sh /app/samvera/hyrax-webapp/solr/conf &&
        solrcloud-assign-configset.sh &&
        SOLR_COLLECTION_NAME=hydra-test solrcloud-assign-configset.sh &&
        db-migrate-seed.sh

  redis:
    extends:
      file: hyrax-webapp/docker-compose.yml
      service: redis

  chrome:
    extends:
      file: hyrax-webapp/docker-compose.yml
      service: chrome
