# Simple yaml config-driven schema which is used to define model attributes,
# index key names, and form properties.
#
# Attributes must have a type but all other configuration options are optional.
# Please note: If using Valkyrie's Fedora Metadata Adapter, predicates for attributes
# must be placed here.
#
# attributes:
#   attribute_name:
#     type: string
#     multiple: false
#     index_keys:
#       - "attribute_name_sim"
#     form:
#       required: true
#       primary: true
#       multiple: false
#
# @see config/metadata/basic_metadata.yaml for an example configuration
#
# Generated via
#  `rails generate hyrax:work_resource UncaWork`

attributes:
  date_accepted:
    type: date
    multiple: false
    index_keys:
      - "date_accepted_tesim"
    form:
      required: false
      primary: false
      multiple: false
    predicate: http://purl.org/dc/terms/dateAccepted
  document_relationship:
    type: string
    multiple: true
    index_keys:
      - "document_relationship_tesim"
    form:
      required: false
      primary: false
      multiple: true
    predicate: http://purl.org/dc/terms/hasPart
  content_type:
    type: string
    multiple: true
    index_keys:
      - "content_type_tesim"
    form:
      required: false
      primary: false
      multiple: true
    predicate: http://purl.org/dc/terms/format
  coverage_geographic:
    type: string
    multiple: true
    index_keys:
      - "coverage_geographic_tesim"
    form:
      required: false
      primary: false
      multiple: true
    predicate: http://purl.org/dc/terms/spatial
  coverage_historic:
    type: string
    multiple: true
    index_keys:
      - "coverage_historic_tesim"
    form:
      required: false
      primary: false
      multiple: true
    predicate: http://purl.org/dc/terms/temporal
  notes:
    type: string
    multiple: true
    index_keys:
      - "notes_tesim"
    form:
      required: false
      primary: false
      multiple: true
    predicate: http://purl.org/dc/terms/description
  item_mask:
    type: string
    multiple: true
    index_keys:
      - "item_mask_tesim"
    form:
      required: false
      primary: false
      multiple: true
    predicate: http://example.org/ns#itemMask
  item_embargo:
    type: date
    multiple: false
    index_keys:
      - "item_embargo_tesim"
    form:
      required: false
      primary: false
      multiple: false
    predicate: http://purl.org/dc/terms/available
  file_name:
    type: string
    multiple: true
    index_keys:
      - "file_name_tesim"
    form:
      required: false
      primary: false
      multiple: true
    predicate: http://example.org/ns#fileName
  thesis_type:
    type: string
    multiple: false
    index_keys:
      - "thesis_type_tesim"
    form:
      required: false
      primary: false
      multiple: false
    predicate: http://example.org/ns#thesisType
  degree_name:
    type: string
    multiple: false
    index_keys:
      - "degree_name_tesim"
    form:
      required: false
      primary: false
      multiple: false
    predicate: http://example.org/ns#degreeName
  degree_level:
    type: string
    multiple: false
    index_keys:
      - "degree_level_tesim"
    form:
      required: false
      primary: false
      multiple: false
    predicate: http://example.org/ns#degreeLevel
  discipline:
    type: string
    multiple: false
    index_keys:
      - "discipline_tesim"
    form:
      required: false
      primary: false
      multiple: false
    predicate: http://example.org/ns#discipline
  advisor_last_name:
    type: string
    multiple: false
    index_keys:
      - "advisor_last_name_tesim"
    form:
      required: false
      primary: false
      multiple: false
    predicate: http://xmlns.com/foaf/0.1/familyName
  advisor_first_name:
    type: string
    multiple: false
    index_keys:
      - "advisor_first_name_tesim"
    form:
      required: false
      primary: false
      multiple: false
    predicate: http://xmlns.com/foaf/0.1/givenName
