# Simple yaml config-driven schema which is used to define model attributes,
# index key names, and form properties.
#
# Attributes must have a type but all other configuration options are optional.
# Please note: If using Valkyrie's Fedora Metadata Adapter, predicates for attributes
# must be placed here.
#
# attributes:
#   attribute_name:
#     type: string
#     multiple: false
#     index_keys:
#       - "attribute_name_sim"
#     form:
#       required: true
#       primary: true
#       multiple: false
#
# @see config/metadata/basic_metadata.yaml for an example configuration
#
# Generated via
#  `rails generate hyrax:work_resource UncaWork`

# Metadata common to Unca's custom work types only
# rails generate hyrax:work_resource UncaWork
attributes:
  date_published:
    type: date
    multiple: false
    index_keys:
      - "date_published_tesim"
    form:
      required: false
      primary: false
      multiple: false
    predicate: http://purl.org/dc/terms/dateAccepted
# ISSN/ISBN
# Relation - hasPart:
# - https://adl.b2.adventistdigitallibrary.org/concern/images/p012908_sutherland_family_1927/edit?locale=en
# - https://adl.b2.adventistdigitallibrary.org/concern/images/p012908_sutherland_family_1927
# https://docs.google.com/spreadsheets/d/14of7w09o2i6sH6wzDvNX8ELyUBKGJJ96/edit?gid=1479095251#gid=1479095251