- name: "UNCA Consortium"
  identifier: "unca"
  excluded_work_types:
    - "MobiusWork"
    - "UncaWork"
- name: "Mobius Consortium"
  identifier: "mobius"
  excluded_work_types:
    - "UncaWork"
    - "ScholarlyWork"



