replicaCount: 2

imagePullSecrets:
  - name: github

resources:
  limits:
    memory: "4Gi"
    cpu: "2"
  requests:
    memory: "2Gi"
    cpu: "1"

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

brandingVolume:
  storageClass: efs-sc
derivativesVolume:
  storageClass: efs-sc
uploadsVolume:
  storageClass: efs-sc

extraVolumeMounts: &volMounts
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/imports
    subPath: imports
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/exports
    subPath: exports
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/public/system
    subPath: public-system
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/public/uploads
    subPath: public-uploads
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/network_files
    subPath: network-files
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/storage/files
    subPath: storage-files
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/log/rack_attack
    subPath: rack-attack

ingress:
  enabled: true
  hosts:
    - host: '*.hykuup.com'
      paths:
        - path: /
  annotations: {
    kubernetes.io/ingress.class: "nginx",
    nginx.ingress.kubernetes.io/proxy-body-size: "0",
    cert-manager.io/cluster-issuer: letsencrypt-production-dns
  }
  tls:
    - secretName: wildcard-tls-secret
      hosts:
        - '*.hykuup.com'

extraEnvVars: &envVars
  - name: BUNDLE_LOCAL__HYKU_KNAPSACK
    value: /app/samvera
  - name: BUNDLE_DISABLE_LOCAL_BRANCH_CHECK
    value: "true"
  - name: CONFDIR
    value: "/app/samvera/hyrax-webapp/solr/conf"
  - name: DB_ADAPTER
    value: postgresql
  - name: DB_ADVISORY_LOCKS
    value: "false"
  - name: DB_PREPARED_STATEMENTS
    value: "false"
  - name: DB_HOST
    value: acid-postgres-cluster-delta.postgres.svc.cluster.local
  - name: DB_NAME
    value: hykuup_production
  - name: DB_PASSWORD
    value: $DB_PASSWORD
  - name: DB_USER
    value: hykuup_production
  - name: DISABLE_SPRING
    value: '1'
  - name: FCREPO_BASE_PATH
    value: /hykuup
  - name: FCREPO_HOST
    value: fcrepo.fcrepo.svc.cluster.local
  - name: FCREPO_REST_PATH
    value: rest
  - name: FCREPO_PATH
    value: /rest
  - name: FCREPO_URL
    value: http://fcrepo.fcrepo.svc.cluster.local:8080/rest
  - name: HYRAX_ANALYTICS
    value: 'true'
  - name: HYRAX_ANALYTICS_PROVIDER
    value: 'ga4'
  - name: GOOGLE_ANALYTICS_ID
    value: $GOOGLE_ANALYTICS_ID
  # - name: GOOGLE_OAUTH_APP_NAME
  #   value: atla-hyku-production
  # - name: GOOGLE_OAUTH_APP_VERSION
  #   value: '1.0'
  # - name: GOOGLE_OAUTH_PRIVATE_KEY_SECRET
  #   value: $GOOGLE_OAUTH_PRIVATE_KEY_SECRET
  # - name: GOOGLE_OAUTH_PRIVATE_KEY_PATH
  #   value: prod-cred.p12
  # - name: GOOGLE_OAUTH_PRIVATE_KEY_VALUE
  #   value: $GOOGLE_OAUTH_PRIVATE_KEY_VALUE
  # - name: GOOGLE_OAUTH_CLIENT_EMAIL
  #   value: hyku-demo@hyku-demo.iam.gserviceaccount.com
  - name: HYRAX_ACTIVE_JOB_QUEUE
    value: good_job
  - name: HYRAX_FITS_PATH
    value: /app/fits/fits.sh
  - name: HYRAX_FLEXIBLE
    value: "true"
  - name: HYRAX_VALKYRIE
    value: "true"
  - name: HYKU_ADMIN_HOST
    value: main.hykuup.com
  - name: HYKU_ADMIN_ONLY_TENANT_CREATION
    value: 'false'
  - name: HYKU_ALLOW_SIGNUP
    value: 'false'
  - name: HYKU_ATTACK_RATE_THROTTLE_OFF
    value: "false"
  - name: HYKU_BULKRAX_ENABLED
    value: 'true'
  - name: HYKU_BLOCK_VALKYRIE_REDIRECT
    value: "false"
  - name: HYKU_CONTACT_EMAIL
    value: info@hykuup.com
  - name: HYKU_CONTACT_EMAIL_TO
    value: info@hykuup.com
  - name: HYKU_DEFAULT_HOST
    value: "%{tenant}.hykuup.com"
  - name: HYKU_ENABLED
    value: "true"
  - name: HYKU_FILE_ACL
    value: "true"
  - name: HYKU_MULTITENANT
    value: "true"
  - name: HYKU_ROOT_HOST
    value: hykuup.com
  - name: INITIAL_ADMIN_EMAIL
    value: $INITIAL_ADMIN_EMAIL
  - name: INITIAL_ADMIN_PASSWORD
    value: $INITIAL_ADMIN_PASSWORD
  - name: HYRAX_USE_SOLR_GRAPH_NESTING
    value: "true"
  - name: IN_DOCKER
    value: "true"
  - name: LD_LIBRARY_PATH
    value: /app/fits/tools/mediainfo/linux
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://alloy.monitoring.svc.cluster.local:4318"
  - name: OTEL_SERVICE_NAME
    value: hykuup-knapsack-production
  - name: PYROSCOPE_SERVER_ADDRESS
    value: "http://alloy.monitoring.svc.cluster.local:4040"
  - name: PASSENGER_APP_ENV
    value: production
  - name: RAILS_CACHE_STORE_URL
    value: redis://:$REDIS_PASSWORD@hykuup-knapsack-production-redis-master:6379/0
  - name: RAILS_ENV
    value: production
  - name: RAILS_LOG_TO_STDOUT
    value: "true"
  - name: RAILS_MAX_THREADS
    value: "5"
  - name: RAILS_SERVE_STATIC_FILES
    value: "true"
  - name: REDIS_HOST
    value: hykuup-knapsack-production-redis-master
  - name: REDIS_PORT
    value: '6379'
  - name: REDIS_PASSWORD
    value: $REDIS_PASSWORD
  - name: REDIS_URL
    value: redis://:$REDIS_PASSWORD@hykuup-knapsack-production-redis-master:6379/0
  - name: SECRET_KEY_BASE
    value: $SECRET_KEY_BASE
  - name: SENTRY_DSN
    value: $SENTRY_DSN
  - name: SENTRY_ENVIRONMENT
    value: "hykuup-knapsack-production"
  - name: SMTP_ADDRESS
    value: smtp.sendgrid.net
  - name: SMTP_DOMAIN
    value: hykuup.com
  - name: SMTP_ENABLED
    value: "true"
  - name: SMTP_PASSWORD
    value: $SMTP_PASSWORD
  - name: SMTP_PORT
    value: "587"
  - name: SMTP_STARTTLS
    value: 'true'
  - name: SMTP_TYPE
    value: plain
  - name: SMTP_USER_NAME
    value: apikey
  - name: SOLR_ADMIN_PASSWORD
    value: $SOLR_ADMIN_PASSWORD
  - name: SOLR_ADMIN_USER
    value: admin
  - name: SOLR_COLLECTION_NAME
    value: hykuup-hyku
  - name: SOLR_CONFIGSET_NAME
    value: hykuup-hyku
  - name: SOLR_HOST
    value: solr-headless.solr
  - name: SOLR_PORT
    value: "8983"
  - name: SOLR_URL
    value: http://admin:$SOLR_ADMIN_PASSWORD@solr-headless.solr:8983/solr/
  - name: SUPPORT_EMAIL
    value: support@notch8.com
  - name: SUPPORT_PASSWORD
    value: testing123
  - name: TEST_USER_EMAIL
    value: user@notch8.com
  - name: TEST_USER_PASSWORD
    value: testing123
  - name: VALKYRIE_ID_TYPE
    value: string
  - name: VALKYRIE_TRANSITION
    value: "true"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://alloy.monitoring.svc.cluster.local:4318"
  - name: PYROSCOPE_SERVER_ADDRESS
    value: "http://alloy.monitoring.svc.cluster.local:4040"

podSecurityContext: &podSecValues
  runAsUser: 1001
  runAsGroup: 101
  fsGroup: 101
  fsGroupChangePolicy: 'OnRootMismatch'

worker:
  replicaCount: 1
  resources:
    limits:
      memory: "6Gi"
      cpu: "3"
    requests:
      memory: "3Gi"
      cpu: "1"
  podSecurityContext:
    runAsUser: 1001
    runAsGroup: 101
    fsGroup: 101
    fsGroupChangePolicy: "OnRootMismatch"
  extraVolumeMounts: *volMounts
  extraEnvVars: *envVars
  podSecurityContext: *podSecValues

embargoRelease:
  enabled: false
leaseRelease:
  enabled: false

fcrepo:
  enabled: false
postgresql:
  enabled: false
redis:
  image:
    repository: bitnamilegacy/redis
    tag: 7.0.2-debian-11-r7
  architecture: standalone
  master:
    persistence:
      enabled: true
      storageClass: gp2
  auth:
    password: $REDIS_PASSWORD

solr:
  enabled: false

externalFcrepoHost: fcrepo.fcrepo.svc.cluster.local
externalPostgresql:
  host: acid-postgres-cluster-delta.postgres.svc.cluster.local
  username: hykuup_production
  password: $DB_PASSWORD
  database: hykuup_production

externalSolrPassword: $SOLR_ADMIN_PASSWORD
externalSolrHost: solr.solr.svc.cluster.local
externalSolrUser: admin
externalSolrCollection: "hykuup-hyku"

nginx:
  enabled: false
  service:
    port: 80
