replicaCount: 2

resources:
  limits:
    memory: "4Gi"
    cpu: "500m"
  requests:
    memory: "2Gi"
    cpu: "250m"

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

brandingVolume:
  storageClass: efs-sc
derivativesVolume:
  storageClass: efs-sc
uploadsVolume:
  storageClass: efs-sc

extraVolumeMounts: &volMounts
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/imports
    subPath: imports
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/exports
    subPath: exports
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/public/system
    subPath: public-system
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/public/uploads
    subPath: public-uploads
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/network_files
    subPath: network-files

ingress:
  enabled: true
  hosts:
    - host: samvera.hykuup.com
      paths:
        - path: /
    - host: '*.hykuup.com'
      paths:
        - path: /
  annotations: {
    kubernetes.io/ingress.class: "nginx",
    nginx.ingress.kubernetes.io/proxy-body-size: "0",
    cert-manager.io/cluster-issuer: letsencrypt-production-dns
  }
  tls:
    - hosts:
        - samvera.hykuup.com
        - "*.hykuup.com"
      secretName: hykuup

extraEnvVars: &envVars
  - name: CONFDIR
    value: "/app/samvera/hyrax-webapp/solr/conf"
  - name: CLIENT_ADMIN_USER_EMAIL
    value: $CLIENT_ADMIN_USER_EMAIL
  - name: CLIENT_ADMIN_USER_PASSWORD
    value: $CLIENT_ADMIN_USER_PASSWORD
  - name: DB_ADAPTER
    value: postgresql
  - name: DB_HOST
    value: acid-postgres-cluster-bravo-pooler.postgres.svc.cluster.local
  - name: DB_NAME
    value:hykuup_production
  - name: DB_PASSWORD
    value: $DB_PASSWORD
  - name: DB_USER
    value: hykuup_production
  - name: DISABLE_SPRING
    value: '1'
  - name: FCREPO_BASE_PATH
    value: /hykuup
  - name: FCREPO_HOST
    value: fcrepo.fcrepo.svc.cluster.local:8080
  - name: FCREPO_REST_PATH
    value: rest
  - name: FCREPO_PATH
    value: /rest
  - name: FCREPO_URL
    value: http://fcrepo.fcrepo.svc.cluster.local:8080/rest
  - name: HYRAX_ANALYTICS
    value: 'false'
  # - name: GOOGLE_ANALYTICS_ID
  #   value: $GOOGLE_ANALYTICS_ID
  # - name: GOOGLE_OAUTH_APP_NAME
  #   value: atla-hyku-production
  # - name: GOOGLE_OAUTH_APP_VERSION
  #   value: '1.0'
  # - name: GOOGLE_OAUTH_PRIVATE_KEY_SECRET
  #   value: $GOOGLE_OAUTH_PRIVATE_KEY_SECRET
  # - name: GOOGLE_OAUTH_PRIVATE_KEY_PATH
  #   value: prod-cred.p12
  # - name: GOOGLE_OAUTH_PRIVATE_KEY_VALUE
  #   value: $GOOGLE_OAUTH_PRIVATE_KEY_VALUE
  # - name: GOOGLE_OAUTH_CLIENT_EMAIL
  #   value: hyku-demo@hyku-demo.iam.gserviceaccount.com
  - name: HYRAX_ACTIVE_JOB_QUEUE
    value: sidekiq
  - name: HYRAX_FITS_PATH
    value: /app/fits/fits.sh
  - name: HYKU_ADMIN_HOST
    value: admin.hykuup.com
  - name: HYKU_ADMIN_ONLY_TENANT_CREATION
    value: 'false'
  - name: HYKU_ALLOW_SIGNUP
    value: 'false'
  - name: HYKU_BULKRAX_ENABLED
    value: 'true'
  - name: HYKU_CONTACT_EMAIL
    value: dev-oops@scientist.com
  - name: HYKU_DEFAULT_HOST
    value: "%{tenant}.hykuup.com"
  - name: HYKU_ENABLED
    value: "true"
  - name: HYKU_FILE_ACL
    value: "true"
  - name: HYKU_MULTITENANT
    value: "true"
  - name: HYKU_ROOT_HOST
    value: hykuup.com
  - name: INITIAL_ADMIN_EMAIL
    value: admin@example.com
  - name: INITIAL_ADMIN_PASSWORD
    value: testing123
  - name: HYRAX_USE_SOLR_GRAPH_NESTING
    value: "true"
  - name: IN_DOCKER
    value: "true"
  - name: LD_LIBRARY_PATH
    value: /app/fits/tools/mediainfo/linux
  - name: PASSENGER_APP_ENV
    value: production
  - name: RAILS_CACHE_STORE_URL
    value: redis://:$REDIS_PASSWORD@hykuup-hyku-production-redis-master:6379/hykuup-hyku
  - name: RAILS_ENV
    value: production
  - name: RAILS_LOG_TO_STDOUT
    value: "true"
  - name: RAILS_MAX_THREADS
    value: "5"
  - name: RAILS_SERVE_STATIC_FILES
    value: "true"
  - name: REDIS_HOST
    value: hykuup-hyku-production-redis-master
  - name: REDIS_PORT
    value: '6379'
  - name: REDIS_PASSWORD
    value: $REDIS_PASSWORD
  - name: REDIS_URL
    value: redis://:$REDIS_PASSWORD@hykuup-hyku-production-redis-master:6379/hykuup-hyku
  - name: ROB_EMAIL
    value: rob@notch8.com
  - name: ROB_PASSWORD
    value: testing123
  - name: SENTRY_DSN
    value: https://ab7f8b39ca414630bd07f6657f57f641@o1008683.ingest.sentry.io/6745049
  - name: SENTRY_ENVIRONMENT
    value: production
  - name: SMTP_ADDRESS
    value: smtp.mailtrap.io
  - name: SMTP_DOMAIN
    value: smtp.mailtrap.io
  - name: SMTP_ENABLED
    value: "true"
  - name: SMTP_PASSWORD
    value: $SMTP_PASSWORD
  - name: SMTP_PORT
    value: "2525"
  - name: SMTP_STARTTLS
    value: 'true'
  - name: SMTP_TYPE
    value: cram_md5
  - name: SMTP_USER_NAME
    value: d930a4455e9287
  - name: SOLR_ADMIN_PASSWORD
    value: $SOLR_ADMIN_PASSWORD
  - name: SOLR_ADMIN_USER
    value: admin
  - name: SOLR_COLLECTION_NAME
    value: hykuup-hyku
  - name: SOLR_CONFIGSET_NAME
    value: hykuup-hyku
  - name: SOLR_HOST
    value: solr-headless.solr
  - name: SOLR_PORT
    value: "8983"
  - name: SOLR_URL
    value: http://admin:$SOLR_ADMIN_PASSWORD@solr-headless.solr:8983/solr/
  - name: SUPPORT_EMAIL
    value: support@notch8.com
  - name: SUPPORT_PASSWORD
    value: testing123
  - name: TEST_USER_EMAIL
    value: user@notch8.com
  - name: TEST_USER_PASSWORD
    value: testing123

securityContext: &secValues
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  runAsUser: 0
podSecurityContext: &podSecValues
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 101
  fsGroup: 101
  fsGroupChangePolicy: 'OnRootMismatch'

worker:
  replicaCount: 1
  resources:
    limits:
      memory: "6Gi"
      cpu: "3"
    requests:
      memory: "3Gi"
      cpu: "1"
  podSecurityContext:
    runAsUser: 1001
    runAsGroup: 101
    fsGroup: 101
    fsGroupChangePolicy: "OnRootMismatch"
  extraVolumeMounts: *volMounts
  extraEnvVars: *envVars
  podSecurityContext: *podSecValues
  securityContext: *secValues

embargoRelease:
  enabled: false
leaseRelease:
  enabled: false

fcrepo:
  enabled: false
postgresql:
  enabled: false

redis:
  persistence:
    enabled: true
    storageClass: ebs
  cluster:
    enabled: false
  password: $REDIS_PASSWORD

solr:
  enabled: false

externalFcrepoHost: fcrepo.fcrepo.svc.cluster.local
externalPostgresql:
  host: acid-postgres-cluster-bravo-pooler.postgres.svc.cluster.local
  username: hykuup_production
  password: $DB_PASSWORD
  database: hykuup_production

externalSolrPassword: $SOLR_ADMIN_PASSWORD
externalSolrHost: solr.solr.svc.cluster.local
externalSolrUser: admin
externalSolrCollection: "hykuup-hyku"

nginx:
  enabled: false
  service:
    port: 80
