replicaCount: 2

# These values are currently in atla_digital_library
# Do we still like these values set?
# resources:
#   requests:
#     memory: '1Gi'
#     cpu: '250m'
#   limits:
#     memory: '2Gi'
#     cpu: '1000m'

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

brandingVolume:
  storageClass: aws-efs
derivativesVolume:
  storageClass: aws-efs
uploadsVolume:
  storageClass: aws-efs
  size: 200Gi

imagePullSecrets:
 - name: github

extraVolumeMounts: &volMounts
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/imports
    subPath: imports
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/exports
    subPath: exports
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/public/system
    subPath: public-system
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/public/uploads
    subPath: public-uploads
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/network_files
    subPath: network-files

ingress:
  enabled: true
  hosts:
    - host: repo.samvera.org
      paths:
        - path: /
    - host: '*.hykuup.com'
      paths:
        - path: /
  tls:
    - secretName: wildcard-tls-secret
      hosts:
        - '*.hykuup.com'
    - secretName: samvera-tls
      hosts:
        - repo.samvera.org

extraEnvVars: &envVars
  - name: CONFDIR
    value: '/app/samvera/hyrax-webapp/solr/conf'
  - name: CLIENT_ADMIN_USER_EMAIL
    value: $CLIENT_ADMIN_USER_EMAIL
  - name: CLIENT_ADMIN_USER_PASSWORD
    value: $CLIENT_ADMIN_USER_PASSWORD
  - name: DB_ADAPTER
    value: postgresql
  - name: DB_HOST
    value: hyrax20181216.cn4nhxyoxlnu.us-west-2.rds.amazonaws.com
  - name: DB_NAME
    value: atla-hyku-production
  - name: DB_USER
    value: hydra_user
  - name: DISABLE_SPRING
    value: '1'
  - name: FCREPO_BASE_PATH
    value: /hykuprod
  - name: FCREPO_HOST
    value: fcrepo.default.svc.cluster.local
  - name: FCREPO_PORT
    value: '8080'
  - name: FCREPO_REST_PATH
    value: rest
  - name: HYRAX_ANALYTICS
    value: 'false'
  # - name: GOOGLE_ANALYTICS_ID
  #   value: $GOOGLE_ANALYTICS_ID
  # - name: GOOGLE_OAUTH_APP_NAME
  #   value: atla-hyku-production
  # - name: GOOGLE_OAUTH_APP_VERSION
  #   value: '1.0'
  # - name: GOOGLE_OAUTH_PRIVATE_KEY_SECRET
  #   value: $GOOGLE_OAUTH_PRIVATE_KEY_SECRET
  # - name: GOOGLE_OAUTH_PRIVATE_KEY_PATH
  #   value: prod-cred.p12
  # - name: GOOGLE_OAUTH_PRIVATE_KEY_VALUE
  #   value: $GOOGLE_OAUTH_PRIVATE_KEY_VALUE
  # - name: GOOGLE_OAUTH_CLIENT_EMAIL
  #   value: hyku-demo@hyku-demo.iam.gserviceaccount.com
  - name: HYRAX_ACTIVE_JOB_QUEUE
    value: sidekiq
  - name: HYRAX_FITS_PATH
    value: /app/fits/fits.sh
  - name: HYKU_ADMIN_HOST
    value: ir.atla.com
  - name: HYKU_ADMIN_ONLY_TENANT_CREATION
    value: 'false'
  - name: HYKU_ALLOW_SIGNUP
    value: 'false'
  - name: HYKU_BULKRAX_ENABLED
    value: 'true'
  - name: HYKU_CONTACT_EMAIL
    value: dev-oops@scientist.com
  - name: HYKU_DEFAULT_HOST
    value: "%{tenant}.ir.atla.com"
  - name: HYKU_FILE_ACL
    value: 'false'
  - name: HYKU_MULTITENANT
    value: 'true'
  - name: HYKU_ROOT_HOST
    value: ir.atla.com
  - name: INITIAL_ADMIN_EMAIL
    value: admin@example.com
  - name: INITIAL_ADMIN_PASSWORD
    value: testing123
  - name: IN_DOCKER
    value: 'true'
  - name: LD_LIBRARY_PATH
    value: /app/fits/tools/mediainfo/linux
  - name: PASSENGER_APP_ENV
    value: production
  - name: RAILS_CACHE_STORE_URL
    value: redis://:$REDIS_PASSWORD@atla-hyku-production-redis-master:6379/hykuprod
  - name: RAILS_ENV
    value: production
  - name: RAILS_LOG_TO_STDOUT
    value: 'true'
  - name: RAILS_MAX_THREADS
    value: '5'
  - name: RAILS_SERVE_STATIC_FILES
    value: 'true'
  - name: REDIS_HOST
    value: atla-hyku-production-redis-master
  - name: REDIS_PORT
    value: '6379'
  - name: REDIS_PASSWORD
    value: $REDIS_PASSWORD
  - name: REDIS_URL
    value: redis://:$REDIS_PASSWORD@atla-hyku-production-redis-master
  - name: SMTP_ADDRESS
    value: email-smtp.us-east-1.amazonaws.com
  - name: SMTP_DOMAIN
    value: atla.com
  - name: SMTP_ENABLED
    value: 'true'
  - name: SMTP_PASSWORD
    value: $SMTP_PASSWORD
  - name: SMTP_PORT
    value: '465'
  - name: SMTP_STARTTLS
    value: 'true'
  - name: SMTP_TYPE
    value: login
  - name: SMTP_USER_NAME
    value: $SMTP_USER_NAME
  - name: SOLR_ADMIN_USER
    value: admin
  - name: SOLR_ADMIN_PASSWORD
    value: $SOLR_ADMIN_PASSWORD
  - name: SOLR_COLLECTION_NAME
    value: atla-hyku-production
  - name: SOLR_CONFIGSET_NAME
    value: atla-hyku-production
  - name: SOLR_HOST
    value: solr.default.svc.cluster.local
  - name: SOLR_PORT
    value: '8983'
  - name: SOLR_URL
    value: http://admin:$SOLR_ADMIN_PASSWORD@solr.default.svc.cluster.local:8983/solr/
  - name: SENTRY_DSN
    value: $SENTRY_DSN
  - name: SENTRY_ENVIRONMENT
    value: $SENTRY_ENVIRONMENT
  - name: TEST_USER_EMAIL
    value: user@example.com
  - name: TEST_USER_PASSWORD
    value: testing123

securityContext: &secValues
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  runAsUser: 0
podSecurityContext: &podSecValues
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 101
  fsGroup: 101
  fsGroupChangePolicy: 'OnRootMismatch'

worker:
  replicaCount: 1
  extraVolumeMounts: *volMounts
  extraEnvVars: *envVars
  podSecurityContext: *podSecValues
  securityContext: *secValues

embargoRelease:
  enabled: false
leaseRelease:
  enabled: false

fcrepo:
  enabled: false
# These values are currently in atla_digital_library
# Do we still like these values set?
  # resources:
  #   limits:
  #     memory: '4Gi'
  #     cpu: '2'
  #   requests:
  #     memory: '2Gi'
  #     cpu: '1'

postgresql:
  enabled: false

redis:
  persistence:
    enabled: true
    storageClass: ebs
  cluster:
    enabled: false
  password: $REDIS_PASSWORD

solr:
  enabled: false

externalFcrepoHost: fcrepo.default.svc.cluster.local

externalPostgresql:
  host: hyrax20181216.cn4nhxyoxlnu.us-west-2.rds.amazonaws.com
  username: hydra_user
  password: $POSTGRES_PASSWORD
  database: atla-hyku-production

externalSolrHost: solr.default.svc.cluster.local
externalSolrUser: admin
externalSolrCollection: 'atla-hyku-production'
externalSolrPassword: $SOLR_ADMIN_PASSWORD

# global:
  # hyraxName: atla-hyku-production-hyrax

nginx:
  enabled: false
  service:
    port: 80
