name: 'Build Test Lint'
run-name: Build Test Lint of ${{ github.ref_name }} by @${{ github.actor }}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:
    uses: scientist-softserv/actions/.github/workflows/build.yaml@make_actions_more_like_local
    secrets: inherit
    with:
      platforms: 'linux/amd64'
      webTarget: hyku-web
      workerTarget: hyku-worker

  test:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/test.yaml@make_actions_more_like_local
    with:
      confdir: '/app/samvera/hyrax-webapp/solr/conf'
      webTarget: hyku-web
      workerTarget: hyku-worker

  lint:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/lint.yaml@make_actions_more_like_local
    with:
      webTarget: hyku-web
      workerTarget: hyku-worker
