name: "Build Test Lint Deploy"
run-name: Build Test Lint of ${{ github.ref_name }} by @${{ github.actor }}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_step:
        required: false
        description: "Pause the selected step to debug using tmate"
        type: choice
        default: ""
        options:
          - ""
          - build
          - test
          - lint

jobs:
  build:
    uses: notch8/actions/.github/workflows/build.yaml@v1.0.3
    secrets: inherit
    with:
      platforms: "linux/amd64"
      webTarget: hyku-web
      workerTarget: hyku-worker
  test:
    needs: build
    uses: notch8/actions/.github/workflows/test.yaml@v1.0.3
    with:
      confdir: "/app/samvera/hyrax-webapp/solr/conf"
      rspec_cmd: "cd .. && gem install semaphore_test_boosters && bundle && rspec_booster --job $CI_NODE_INDEX/$CI_NODE_TOTAL"

  lint:
    needs: build
    uses: notch8/actions/.github/workflows/lint.yaml@v1.0.3
    with:
      webTarget: hyku-web
      workerTarget: hyku-worker
      rubocop_cmd: "cd .. && bundle && bundle exec rubocop --parallel --format progress"

  update-deploy-values:
    needs: build
    # TODO: replace add-new-deploy-action with main after that branch has been merged
    uses: notch8/actions/.github/workflows/update-deploy-values.yaml@v1.0.3
    secrets: inherit # required to read org-level secrets used by action
    with:
      ops_repository: ${{ vars.OPS_REPOSITORY }}
