name: "Build Solr"
run-name: Build Solr of ${{ github.ref_name }} by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:
    uses: scientist-softserv/actions/.github/workflows/build.yaml@make_actions_more_like_local
    secrets: inherit
    with:
      platforms: "linux/amd64"
      solrTarget: hyku-solr
